name: Update README

on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Misly16/Misly16@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
